package com.met.atims_reporter.model

data class CrashReport(
    var source: String = "MOB",
    var user_id: String = "",
    var companyId: String = "",
    var crash_report_data_id: String = "",
    var company_user_id: String = "",
    var vehicle_id: String,
    var vehicleId: String = "",
    var state_id: String,
    var state_name: String = "",
    var latitude: String,
    var longitude: String,
    var crash_report_date: String,
    var crash_report_time: String,
    var self_injured: String,
    var other_injured: String,
    var number_of_injured_people: String,
    var contacted_tmc: String,
    var contacted_supervisor: String,
    var you_inside_truck: String,
    var safety_belt: String,
    var police_report: String,
    var written_statement: String = "",
    var exterior_vehicle_photo1: String = "",
    var exterior_vehicle_photo2: String = "",
    var exterior_vehicle_photo3: String = "",
    var exterior_vehicle_photo4: String = "",
    var interior_vehicle_photo1: String = "",
    var interior_vehicle_photo2: String = "",
    var interior_vehicle_photo3: String = "",
    var interior_vehicle_photo4: String = "",
    var autotag_vin_photo1: String = "",
    var autotag_vin_photo2: String = "",
    var autotag_vin_photo3: String = "",
    var autotag_vin_photo4: String = "",
    var third_party_vehicle_photo1: String = "",
    var third_party_vehicle_photo2: String = "",
    var third_party_vehicle_photo3: String = "",
    var third_party_vehicle_photo4: String = "",
    var driver_info: ArrayList<CrashReportDriverInfo> = ArrayList(),
    var imagePaths: ArrayList<ArrayList<String>> = ArrayList(),
    var anyPropertyDamaged: Boolean = true,
    var thirdPartyVehicleAvailable: Boolean = true,
    var operator_shift_time_details_id: String = ""
)