package com.met.atims_reporter.model

data class MotoristVehicleModel(
    var vehicle_id: String,
    var vehicle_type_id: String,
    var device_id: String,
    var state_id: String,
    var operation_area_id: String,
    var company_id: String,
    var ID: String,
    var name: String,
    var no_year: String,
    var make: String,
    var vin_number: String,
    var model: String,
    var registration_no: String,
    var license_no: String,
    var color: String,
    var insurance_expiary_date: String,
    var state_inspection_expirary_date: String,
    var front_photo: String,
    var back_photo: String,
    var left_photo: String,
    var right_photo: String,
    var isFleet: String,
    var status: String,
    var created_by: String,
    var created_ts: String,
    var updated_by: String,
    var updated_ts: String,
    var is_delete: String,
    var type_name: String,
    var state_name: String,
    var operation_area_name: String
)